# Generated by Django 2.2a1 on 2019-06-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20190616_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='special_offer',
            field=models.BooleanField(default='False'),
        ),
    ]
