# Generated by Django 2.2a1 on 2019-06-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20190620_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
