# Generated by Django 2.2a1 on 2019-06-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20190620_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='dob',
            field=models.DateField(default='off'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.IntegerField(max_length=20),
        ),
    ]
