# Generated by Django 2.2a1 on 2019-06-21 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20190621_1519'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
